### ISSUE TITLE
[Back] Normal User to Notarized User

### ISSUE THREAD

**Issue by JeongOhKye** [KAIST-IS521/TeamFive#20]
Normal User를 Notarized User로 Update시키는 기능

1. Normal User가 로그인을 한다.
1. {userid:GithubID, pubkey:PublicKey} json 형식을 notary service에서 sign을 받아온다
2. Sign된 파일을 올리면 이를 확인하여 Normal User를 Notarized User로 올려준다.

**Comment by blukat29** [comment]
This is duplicated issue with #10.
