### ISSUE TITLE
[bot]Set cross domain cookie

### ISSUE THREAD

**Issue by donghwan17** [KAIST-IS521/TeamFive#24]
The bot should have a cookie originated from a virtual web site, "bank.com".

**Comment by donghwan17** [comment]
webdriver에 쿠키 설정할 때, 현재 접속중인 도메인이 아닌 다른 도메인을 입력하면 에러가 나네요. 
브라우저 single origin policy 설정을 꺼도 안되고.. 쉽지 않네요. 
타도메인 쿠기 읽는 것도 생각해야하는데 잘 안되어서 딜레이 중입니다.

**Comment by sangkilc** [comment]
각자 팀에서 conf 파일 등을 통해 flag에 해당하는 주소를 셋업할 수 있도록 하면 좋겠습니다. 예를 들어 팀1에서는 bank.team1.com 을 configuration 파일에 넣어놓으면, 해당 웹사이트에 쿠키를 만들어서 플래그값을 거기에 저장하는 거죠. 물론 그 사이트는 실제로 존재한다는 가정입니다.

**Comment by donghwan17** [comment]
@sangkilc 조언 감사합니다. 그런데, "실제로 존재한다는 가정"이라는 말씀은 CTF 때는 Team0측에서 해당 웹사이트를 올려 놓을것이라는 의미로 해석해도 되나요?

**Comment by sangkilc** [comment]
네
