### ISSUE TITLE
[CROSS-TEAM] Notary key

### ISSUE THREAD

**Issue by oxsignal** [KAIST-IS521/TeamFive#3]
Government will need our public key to verify our signature.

I attached our Notary key below:

http://pgp.mit.edu/pks/lookup?search=IS521_notary&op=index

Also, you may lookup our pulbic key by searching:
ID : IS521_notary
E-mail : IS521_notary@kaist.ac.kr (This is not a real mail, please don't send any mail to this address)

**Comment by blukat29** [comment]
Thanks.
I will close this issue when we have completed the Notary verification.
