### ISSUE TITLE
[bot] Exception handling 

### ISSUE THREAD

**Issue by donghwan17** [KAIST-IS521/TeamFive#30]
Webdriver에 예상치 못한 결과로인해 오류가 나는 것을 방지한다.
- 게시물에 삽입된 JS로 인하여 alert 발생 시 추가적인 게시물 조회 불가능한 상황 발생
- 그 외 브라우저 화면의 element를 로딩하는데 발생하는 딜레이로 인한 오류 등 
   전반적인 exception 처리가 필요

**Comment by blukat29** [comment]
Timeout을 사용하는 것도 좋은 방법 같습니다.

**Comment by donghwan17** [comment]
네, 그방법을 써야할거 같아요. 
다만 페이지 열 때마다 alert 존재 유무를 확인하기 위해 wait을 하게되면 게시물이 많은 경우 시간이 많이걸릴거 같아요. 게시물당 1초씩 alert에 대한 wait을 추가할 생각이에요.
