### ISSUE TITLE
[Front] About No Title List

### ISSUE THREAD

**Issue by mikkang** [KAIST-IS521/TeamFive#31]
Title이 없는 Post는 어떻게 처리할지?

1. 못쓰게 한다.
2. List에서 클릭을 통해 접근할 수 있도록 List쪽 수정

일단 지금은, Title이나 Content가 공백이어도 저장이 되고
Title이 공백이면, 지금 UI에서는 이름 클릭을 통한 Read가 안 됨. 직접 들어가야함

**Comment by blukat29** [comment]
1번이 간단해서 좋아보이네요

**Comment by donghwan17** [comment]
저도 1번. App이나 DB에서 공백인 경우 Write 실패하는게 좋을거 같아요
