### ISSUE TITLE
[Bot] Remove geckodriver binary

### ISSUE THREAD

**Issue by mikkang** [KAIST-IS521/TeamFive#34]
바이너리를 repo에 안올리고 Makefile에 추가하는게 좋을거 같아요.

**Comment by donghwan17** [comment]
@mikkang 음... 어떤 방법으로 Makefile에 추가하면 될까요? wget 같은걸로 받는 방법인가요?

**Comment by blukat29** [comment]
바이너리를 어디서 가져오신 건가요? https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux32.tar.gz 이건가요?
그렇다면 wget으로 가져오는걸로 바꿔주시면 좋겠네요.

**Comment by donghwan17** [comment]
@blukat29 네 맞아요
