### ISSUE TITLE
[Back] Normal login

### ISSUE THREAD

**Issue by blukat29** [KAIST-IS521/TeamFive#9]
수강생이 PGP 키를 이용해 게시판에 로그인할 수 있도록 한다. 이 기능이 완성될 때까지는 일단 Board는 누구나 볼 수 있고, 누구나 작성, 수정, 삭제할 수 있다. 자세한 구현 방식은 3팀의 구현에 맞춰서 정한다.

**Comment by blukat29** [comment]
<https://github.com/KAIST-IS521/2017-Spring/issues/127>과 <https://github.com/KAIST-IS521/2017-Spring/commit/0e81299c7a714b0034d274b4be779d66e2c0e07d>로 인해
인증 방식을 우리가 원하는 대로 정의할 수 있게 되었습니다.

따라서 아래와 같은 인증 메커니즘을 만들고자 합니다.


| Client                | Server |
| ------                | ------ |
| `/auth` 페이지에 접속 |        |
| | Github ID를 입력하는 화면을 출력 |
| Github ID를 입력하여 `/auth/challenge`에 POST 요청 | |
| | id를 보고 student public key 중에서 해당하는 키 `K_id` 를 찾음 |
| | 랜덤한 nonce `N`을 생성 |
| | id와 nonce값을 각각 세션의 `auth_id` 및 `auth_nonce`로 저장 |
| | nonce를 `K_id`로 암호화한 `E(K_id, N)` 및 서버의 공개키 `K_s`를 보여주면서 입력을 하나 받을 수 있는 창을 출력 |
| `E(K_id, N)`를 본인의 비밀키로 복호화하여 N을 구한다 | |
| N을 `K_s`로 암호화한 `E(K_s, N)`을 입력하여 `/auth/response`에 POST 요청 | |
| | `E(K_s, N)`을 서버의 비밀키로 복호화해 세션에 저장된 `auth_nonce`값과 비교 |
| | 세션에 저장된 `auth_id`를 세션의 `login_user`로 세팅 |
| | BoardUser 테이블에 해당 유저가 없을 경우 계정을 자동 생성하여 DB에 추가 |
| | 홈 페이지로 리디렉션 |

**Comment by blukat29** [comment]
이제 bbs의 모든 view들은 시작 부분에 `request.session["login_user"]`가 있는 지 체크 하고 없으면 `/auth`로 리디렉션 해야 합니다.

**Comment by JeongOhKye** [comment]
generate_challenge 함수에서 1개의 pub키만 있을 경우를 가정하고 진행하고 있어 일부경우 다른키로 encrypt되는 문제 발생

Patched in 315064668336bc0c0a5979d16288c964f54d5563.
